### ISSUE TITLE
Allow supplying of custom JsonSerilalizerSettings 

### ISSUE THREAD

**Issue by keannan5390** [redarrowlabs/Argo#43]
It would be nice to be able to specify custom JsonSerializerSettings for Argo. A key example of this would be to utilize the NodaTime Json Serialization library for NodaTime properties on models.

**Comment by engenb** [comment]
there are two aspects to this:

1. argo uses newtonsoft.json when serializing model values into the underlying json resource.  allowing a way to provide serializer settings should be pretty straight forward

2. when values are converted to strings for query/filter clauses, this does not use newtonsoft.json because the resulting filter string is not json.  I could, however, investigate JValue as a way to consistently convert values to string.  this would also allow me to plug in any configured serializer settings.
